/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachingRouteImport } from './routes/_authenticated/coaching'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback.index'
import { Route as AuthenticatedReportsSchedulesRouteImport } from './routes/_authenticated/reports.schedules'
import { Route as AuthenticatedPortalIdRouteImport } from './routes/_authenticated/portal.$id'
import { Route as AuthenticatedFeedbackNewRouteImport } from './routes/_authenticated/feedback.new'
import { Route as AuthenticatedFeedbackIdRouteImport } from './routes/_authenticated/feedback.$id'
import { Route as AuthenticatedCoachingPlansRouteImport } from './routes/_authenticated/coaching.plans'
import { Route as AuthenticatedCoachingNewRouteImport } from './routes/_authenticated/coaching.new'
import { Route as AuthenticatedCoachingIdRouteImport } from './routes/_authenticated/coaching.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksFeedbackEscalationsRouteImport } from './routes/api/public/hooks/feedback-escalations'
import { Route as ApiPublicHooksDrainEmailQueueRouteImport } from './routes/api/public/hooks/drain-email-queue'
import { Route as ApiPublicHooksDispatchScheduledReportsRouteImport } from './routes/api/public/hooks/dispatch-scheduled-reports'
import { Route as AuthenticatedCoachingPlansNewRouteImport } from './routes/_authenticated/coaching.plans.new'
import { Route as AuthenticatedCoachingPlansIdRouteImport } from './routes/_authenticated/coaching.plans.$id'
import { Route as ApiPublicTrackOpenIdRouteImport } from './routes/api/public/track/open.$id'
import { Route as ApiPublicTrackClickIdRouteImport } from './routes/api/public/track/click.$id'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachingRoute = AuthenticatedCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSchedulesRoute =
  AuthenticatedReportsSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPortalIdRoute = AuthenticatedPortalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedFeedbackNewRoute =
  AuthenticatedFeedbackNewRouteImport.update({
    id: '/feedback/new',
    path: '/feedback/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackIdRoute = AuthenticatedFeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachingPlansRoute =
  AuthenticatedCoachingPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedCoachingRoute,
  } as any)
const AuthenticatedCoachingNewRoute =
  AuthenticatedCoachingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCoachingRoute,
  } as any)
const AuthenticatedCoachingIdRoute = AuthenticatedCoachingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCoachingRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFeedbackEscalationsRoute =
  ApiPublicHooksFeedbackEscalationsRouteImport.update({
    id: '/api/public/hooks/feedback-escalations',
    path: '/api/public/hooks/feedback-escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainEmailQueueRoute =
  ApiPublicHooksDrainEmailQueueRouteImport.update({
    id: '/api/public/hooks/drain-email-queue',
    path: '/api/public/hooks/drain-email-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchScheduledReportsRoute =
  ApiPublicHooksDispatchScheduledReportsRouteImport.update({
    id: '/api/public/hooks/dispatch-scheduled-reports',
    path: '/api/public/hooks/dispatch-scheduled-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCoachingPlansNewRoute =
  AuthenticatedCoachingPlansNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCoachingPlansRoute,
  } as any)
const AuthenticatedCoachingPlansIdRoute =
  AuthenticatedCoachingPlansIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCoachingPlansRoute,
  } as any)
const ApiPublicTrackOpenIdRoute = ApiPublicTrackOpenIdRouteImport.update({
  id: '/api/public/track/open/$id',
  path: '/api/public/track/open/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackClickIdRoute = ApiPublicTrackClickIdRouteImport.update({
  id: '/api/public/track/click/$id',
  path: '/api/public/track/click/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/coaching': typeof AuthenticatedCoachingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/coaching/$id': typeof AuthenticatedCoachingIdRoute
  '/coaching/new': typeof AuthenticatedCoachingNewRoute
  '/coaching/plans': typeof AuthenticatedCoachingPlansRouteWithChildren
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/coaching/plans/$id': typeof AuthenticatedCoachingPlansIdRoute
  '/coaching/plans/new': typeof AuthenticatedCoachingPlansNewRoute
  '/api/public/hooks/dispatch-scheduled-reports': typeof ApiPublicHooksDispatchScheduledReportsRoute
  '/api/public/hooks/drain-email-queue': typeof ApiPublicHooksDrainEmailQueueRoute
  '/api/public/hooks/feedback-escalations': typeof ApiPublicHooksFeedbackEscalationsRoute
  '/api/public/track/click/$id': typeof ApiPublicTrackClickIdRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/coaching': typeof AuthenticatedCoachingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/coaching/$id': typeof AuthenticatedCoachingIdRoute
  '/coaching/new': typeof AuthenticatedCoachingNewRoute
  '/coaching/plans': typeof AuthenticatedCoachingPlansRouteWithChildren
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/coaching/plans/$id': typeof AuthenticatedCoachingPlansIdRoute
  '/coaching/plans/new': typeof AuthenticatedCoachingPlansNewRoute
  '/api/public/hooks/dispatch-scheduled-reports': typeof ApiPublicHooksDispatchScheduledReportsRoute
  '/api/public/hooks/drain-email-queue': typeof ApiPublicHooksDrainEmailQueueRoute
  '/api/public/hooks/feedback-escalations': typeof ApiPublicHooksFeedbackEscalationsRoute
  '/api/public/track/click/$id': typeof ApiPublicTrackClickIdRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/coaching': typeof AuthenticatedCoachingRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/coaching/$id': typeof AuthenticatedCoachingIdRoute
  '/_authenticated/coaching/new': typeof AuthenticatedCoachingNewRoute
  '/_authenticated/coaching/plans': typeof AuthenticatedCoachingPlansRouteWithChildren
  '/_authenticated/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/_authenticated/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/_authenticated/portal/$id': typeof AuthenticatedPortalIdRoute
  '/_authenticated/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/coaching/plans/$id': typeof AuthenticatedCoachingPlansIdRoute
  '/_authenticated/coaching/plans/new': typeof AuthenticatedCoachingPlansNewRoute
  '/api/public/hooks/dispatch-scheduled-reports': typeof ApiPublicHooksDispatchScheduledReportsRoute
  '/api/public/hooks/drain-email-queue': typeof ApiPublicHooksDrainEmailQueueRoute
  '/api/public/hooks/feedback-escalations': typeof ApiPublicHooksFeedbackEscalationsRoute
  '/api/public/track/click/$id': typeof ApiPublicTrackClickIdRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/coaching'
    | '/dashboard'
    | '/health'
    | '/notifications'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/coaching/$id'
    | '/coaching/new'
    | '/coaching/plans'
    | '/feedback/$id'
    | '/feedback/new'
    | '/portal/$id'
    | '/reports/schedules'
    | '/feedback/'
    | '/coaching/plans/$id'
    | '/coaching/plans/new'
    | '/api/public/hooks/dispatch-scheduled-reports'
    | '/api/public/hooks/drain-email-queue'
    | '/api/public/hooks/feedback-escalations'
    | '/api/public/track/click/$id'
    | '/api/public/track/open/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/coaching'
    | '/dashboard'
    | '/health'
    | '/notifications'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/coaching/$id'
    | '/coaching/new'
    | '/coaching/plans'
    | '/feedback/$id'
    | '/feedback/new'
    | '/portal/$id'
    | '/reports/schedules'
    | '/feedback'
    | '/coaching/plans/$id'
    | '/coaching/plans/new'
    | '/api/public/hooks/dispatch-scheduled-reports'
    | '/api/public/hooks/drain-email-queue'
    | '/api/public/hooks/feedback-escalations'
    | '/api/public/track/click/$id'
    | '/api/public/track/open/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/approvals'
    | '/_authenticated/coaching'
    | '/_authenticated/dashboard'
    | '/_authenticated/health'
    | '/_authenticated/notifications'
    | '/_authenticated/portal'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/coaching/$id'
    | '/_authenticated/coaching/new'
    | '/_authenticated/coaching/plans'
    | '/_authenticated/feedback/$id'
    | '/_authenticated/feedback/new'
    | '/_authenticated/portal/$id'
    | '/_authenticated/reports/schedules'
    | '/_authenticated/feedback/'
    | '/_authenticated/coaching/plans/$id'
    | '/_authenticated/coaching/plans/new'
    | '/api/public/hooks/dispatch-scheduled-reports'
    | '/api/public/hooks/drain-email-queue'
    | '/api/public/hooks/feedback-escalations'
    | '/api/public/track/click/$id'
    | '/api/public/track/open/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksDispatchScheduledReportsRoute: typeof ApiPublicHooksDispatchScheduledReportsRoute
  ApiPublicHooksDrainEmailQueueRoute: typeof ApiPublicHooksDrainEmailQueueRoute
  ApiPublicHooksFeedbackEscalationsRoute: typeof ApiPublicHooksFeedbackEscalationsRoute
  ApiPublicTrackClickIdRoute: typeof ApiPublicTrackClickIdRoute
  ApiPublicTrackOpenIdRoute: typeof ApiPublicTrackOpenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaching': {
      id: '/_authenticated/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof AuthenticatedCoachingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/schedules': {
      id: '/_authenticated/reports/schedules'
      path: '/schedules'
      fullPath: '/reports/schedules'
      preLoaderRoute: typeof AuthenticatedReportsSchedulesRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/portal/$id': {
      id: '/_authenticated/portal/$id'
      path: '/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof AuthenticatedPortalIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/feedback/new': {
      id: '/_authenticated/feedback/new'
      path: '/feedback/new'
      fullPath: '/feedback/new'
      preLoaderRoute: typeof AuthenticatedFeedbackNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/$id': {
      id: '/_authenticated/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof AuthenticatedFeedbackIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaching/plans': {
      id: '/_authenticated/coaching/plans'
      path: '/plans'
      fullPath: '/coaching/plans'
      preLoaderRoute: typeof AuthenticatedCoachingPlansRouteImport
      parentRoute: typeof AuthenticatedCoachingRoute
    }
    '/_authenticated/coaching/new': {
      id: '/_authenticated/coaching/new'
      path: '/new'
      fullPath: '/coaching/new'
      preLoaderRoute: typeof AuthenticatedCoachingNewRouteImport
      parentRoute: typeof AuthenticatedCoachingRoute
    }
    '/_authenticated/coaching/$id': {
      id: '/_authenticated/coaching/$id'
      path: '/$id'
      fullPath: '/coaching/$id'
      preLoaderRoute: typeof AuthenticatedCoachingIdRouteImport
      parentRoute: typeof AuthenticatedCoachingRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/feedback-escalations': {
      id: '/api/public/hooks/feedback-escalations'
      path: '/api/public/hooks/feedback-escalations'
      fullPath: '/api/public/hooks/feedback-escalations'
      preLoaderRoute: typeof ApiPublicHooksFeedbackEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-email-queue': {
      id: '/api/public/hooks/drain-email-queue'
      path: '/api/public/hooks/drain-email-queue'
      fullPath: '/api/public/hooks/drain-email-queue'
      preLoaderRoute: typeof ApiPublicHooksDrainEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-scheduled-reports': {
      id: '/api/public/hooks/dispatch-scheduled-reports'
      path: '/api/public/hooks/dispatch-scheduled-reports'
      fullPath: '/api/public/hooks/dispatch-scheduled-reports'
      preLoaderRoute: typeof ApiPublicHooksDispatchScheduledReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coaching/plans/new': {
      id: '/_authenticated/coaching/plans/new'
      path: '/new'
      fullPath: '/coaching/plans/new'
      preLoaderRoute: typeof AuthenticatedCoachingPlansNewRouteImport
      parentRoute: typeof AuthenticatedCoachingPlansRoute
    }
    '/_authenticated/coaching/plans/$id': {
      id: '/_authenticated/coaching/plans/$id'
      path: '/$id'
      fullPath: '/coaching/plans/$id'
      preLoaderRoute: typeof AuthenticatedCoachingPlansIdRouteImport
      parentRoute: typeof AuthenticatedCoachingPlansRoute
    }
    '/api/public/track/open/$id': {
      id: '/api/public/track/open/$id'
      path: '/api/public/track/open/$id'
      fullPath: '/api/public/track/open/$id'
      preLoaderRoute: typeof ApiPublicTrackOpenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click/$id': {
      id: '/api/public/track/click/$id'
      path: '/api/public/track/click/$id'
      fullPath: '/api/public/track/click/$id'
      preLoaderRoute: typeof ApiPublicTrackClickIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCoachingPlansRouteChildren {
  AuthenticatedCoachingPlansIdRoute: typeof AuthenticatedCoachingPlansIdRoute
  AuthenticatedCoachingPlansNewRoute: typeof AuthenticatedCoachingPlansNewRoute
}

const AuthenticatedCoachingPlansRouteChildren: AuthenticatedCoachingPlansRouteChildren =
  {
    AuthenticatedCoachingPlansIdRoute: AuthenticatedCoachingPlansIdRoute,
    AuthenticatedCoachingPlansNewRoute: AuthenticatedCoachingPlansNewRoute,
  }

const AuthenticatedCoachingPlansRouteWithChildren =
  AuthenticatedCoachingPlansRoute._addFileChildren(
    AuthenticatedCoachingPlansRouteChildren,
  )

interface AuthenticatedCoachingRouteChildren {
  AuthenticatedCoachingIdRoute: typeof AuthenticatedCoachingIdRoute
  AuthenticatedCoachingNewRoute: typeof AuthenticatedCoachingNewRoute
  AuthenticatedCoachingPlansRoute: typeof AuthenticatedCoachingPlansRouteWithChildren
}

const AuthenticatedCoachingRouteChildren: AuthenticatedCoachingRouteChildren = {
  AuthenticatedCoachingIdRoute: AuthenticatedCoachingIdRoute,
  AuthenticatedCoachingNewRoute: AuthenticatedCoachingNewRoute,
  AuthenticatedCoachingPlansRoute: AuthenticatedCoachingPlansRouteWithChildren,
}

const AuthenticatedCoachingRouteWithChildren =
  AuthenticatedCoachingRoute._addFileChildren(
    AuthenticatedCoachingRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalIdRoute: typeof AuthenticatedPortalIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalIdRoute: AuthenticatedPortalIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsSchedulesRoute: typeof AuthenticatedReportsSchedulesRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsSchedulesRoute: AuthenticatedReportsSchedulesRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCoachingRoute: typeof AuthenticatedCoachingRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedFeedbackIdRoute: typeof AuthenticatedFeedbackIdRoute
  AuthenticatedFeedbackNewRoute: typeof AuthenticatedFeedbackNewRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCoachingRoute: AuthenticatedCoachingRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedFeedbackIdRoute: AuthenticatedFeedbackIdRoute,
  AuthenticatedFeedbackNewRoute: AuthenticatedFeedbackNewRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksDispatchScheduledReportsRoute:
    ApiPublicHooksDispatchScheduledReportsRoute,
  ApiPublicHooksDrainEmailQueueRoute: ApiPublicHooksDrainEmailQueueRoute,
  ApiPublicHooksFeedbackEscalationsRoute:
    ApiPublicHooksFeedbackEscalationsRoute,
  ApiPublicTrackClickIdRoute: ApiPublicTrackClickIdRoute,
  ApiPublicTrackOpenIdRoute: ApiPublicTrackOpenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
