/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachingRouteImport } from './routes/_authenticated/coaching'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedReportsSchedulesRouteImport } from './routes/_authenticated/reports.schedules'
import { Route as AuthenticatedFeedbackNewRouteImport } from './routes/_authenticated/feedback.new'
import { Route as AuthenticatedFeedbackIdRouteImport } from './routes/_authenticated/feedback.$id'
import { Route as AuthenticatedCoachingNewRouteImport } from './routes/_authenticated/coaching.new'
import { Route as AuthenticatedCoachingIdRouteImport } from './routes/_authenticated/coaching.$id'
import { Route as ApiPublicHooksFeedbackEscalationsRouteImport } from './routes/api/public/hooks/feedback-escalations'
import { Route as ApiPublicHooksDrainEmailQueueRouteImport } from './routes/api/public/hooks/drain-email-queue'
import { Route as ApiPublicHooksDispatchScheduledReportsRouteImport } from './routes/api/public/hooks/dispatch-scheduled-reports'
import { Route as ApiPublicTrackOpenIdRouteImport } from './routes/api/public/track/open.$id'
import { Route as ApiPublicTrackClickIdRouteImport } from './routes/api/public/track/click.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachingRoute = AuthenticatedCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsSchedulesRoute =
  AuthenticatedReportsSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedFeedbackNewRoute =
  AuthenticatedFeedbackNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedFeedbackRoute,
  } as any)
const AuthenticatedFeedbackIdRoute = AuthenticatedFeedbackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFeedbackRoute,
} as any)
const AuthenticatedCoachingNewRoute =
  AuthenticatedCoachingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCoachingRoute,
  } as any)
const AuthenticatedCoachingIdRoute = AuthenticatedCoachingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCoachingRoute,
} as any)
const ApiPublicHooksFeedbackEscalationsRoute =
  ApiPublicHooksFeedbackEscalationsRouteImport.update({
    id: '/api/public/hooks/feedback-escalations',
    path: '/api/public/hooks/feedback-escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainEmailQueueRoute =
  ApiPublicHooksDrainEmailQueueRouteImport.update({
    id: '/api/public/hooks/drain-email-queue',
    path: '/api/public/hooks/drain-email-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchScheduledReportsRoute =
  ApiPublicHooksDispatchScheduledReportsRouteImport.update({
    id: '/api/public/hooks/dispatch-scheduled-reports',
    path: '/api/public/hooks/dispatch-scheduled-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackOpenIdRoute = ApiPublicTrackOpenIdRouteImport.update({
  id: '/api/public/track/open/$id',
  path: '/api/public/track/open/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackClickIdRoute = ApiPublicTrackClickIdRouteImport.update({
  id: '/api/public/track/click/$id',
  path: '/api/public/track/click/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/coaching': typeof AuthenticatedCoachingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/coaching/$id': typeof AuthenticatedCoachingIdRoute
  '/coaching/new': typeof AuthenticatedCoachingNewRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/api/public/hooks/dispatch-scheduled-reports': typeof ApiPublicHooksDispatchScheduledReportsRoute
  '/api/public/hooks/drain-email-queue': typeof ApiPublicHooksDrainEmailQueueRoute
  '/api/public/hooks/feedback-escalations': typeof ApiPublicHooksFeedbackEscalationsRoute
  '/api/public/track/click/$id': typeof ApiPublicTrackClickIdRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/coaching': typeof AuthenticatedCoachingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/coaching/$id': typeof AuthenticatedCoachingIdRoute
  '/coaching/new': typeof AuthenticatedCoachingNewRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/api/public/hooks/dispatch-scheduled-reports': typeof ApiPublicHooksDispatchScheduledReportsRoute
  '/api/public/hooks/drain-email-queue': typeof ApiPublicHooksDrainEmailQueueRoute
  '/api/public/hooks/feedback-escalations': typeof ApiPublicHooksFeedbackEscalationsRoute
  '/api/public/track/click/$id': typeof ApiPublicTrackClickIdRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/coaching': typeof AuthenticatedCoachingRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/coaching/$id': typeof AuthenticatedCoachingIdRoute
  '/_authenticated/coaching/new': typeof AuthenticatedCoachingNewRoute
  '/_authenticated/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/_authenticated/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/_authenticated/reports/schedules': typeof AuthenticatedReportsSchedulesRoute
  '/api/public/hooks/dispatch-scheduled-reports': typeof ApiPublicHooksDispatchScheduledReportsRoute
  '/api/public/hooks/drain-email-queue': typeof ApiPublicHooksDrainEmailQueueRoute
  '/api/public/hooks/feedback-escalations': typeof ApiPublicHooksFeedbackEscalationsRoute
  '/api/public/track/click/$id': typeof ApiPublicTrackClickIdRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/analytics'
    | '/coaching'
    | '/dashboard'
    | '/feedback'
    | '/reports'
    | '/settings'
    | '/coaching/$id'
    | '/coaching/new'
    | '/feedback/$id'
    | '/feedback/new'
    | '/reports/schedules'
    | '/api/public/hooks/dispatch-scheduled-reports'
    | '/api/public/hooks/drain-email-queue'
    | '/api/public/hooks/feedback-escalations'
    | '/api/public/track/click/$id'
    | '/api/public/track/open/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/analytics'
    | '/coaching'
    | '/dashboard'
    | '/feedback'
    | '/reports'
    | '/settings'
    | '/coaching/$id'
    | '/coaching/new'
    | '/feedback/$id'
    | '/feedback/new'
    | '/reports/schedules'
    | '/api/public/hooks/dispatch-scheduled-reports'
    | '/api/public/hooks/drain-email-queue'
    | '/api/public/hooks/feedback-escalations'
    | '/api/public/track/click/$id'
    | '/api/public/track/open/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/coaching'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/coaching/$id'
    | '/_authenticated/coaching/new'
    | '/_authenticated/feedback/$id'
    | '/_authenticated/feedback/new'
    | '/_authenticated/reports/schedules'
    | '/api/public/hooks/dispatch-scheduled-reports'
    | '/api/public/hooks/drain-email-queue'
    | '/api/public/hooks/feedback-escalations'
    | '/api/public/track/click/$id'
    | '/api/public/track/open/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksDispatchScheduledReportsRoute: typeof ApiPublicHooksDispatchScheduledReportsRoute
  ApiPublicHooksDrainEmailQueueRoute: typeof ApiPublicHooksDrainEmailQueueRoute
  ApiPublicHooksFeedbackEscalationsRoute: typeof ApiPublicHooksFeedbackEscalationsRoute
  ApiPublicTrackClickIdRoute: typeof ApiPublicTrackClickIdRoute
  ApiPublicTrackOpenIdRoute: typeof ApiPublicTrackOpenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaching': {
      id: '/_authenticated/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof AuthenticatedCoachingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/schedules': {
      id: '/_authenticated/reports/schedules'
      path: '/schedules'
      fullPath: '/reports/schedules'
      preLoaderRoute: typeof AuthenticatedReportsSchedulesRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/feedback/new': {
      id: '/_authenticated/feedback/new'
      path: '/new'
      fullPath: '/feedback/new'
      preLoaderRoute: typeof AuthenticatedFeedbackNewRouteImport
      parentRoute: typeof AuthenticatedFeedbackRoute
    }
    '/_authenticated/feedback/$id': {
      id: '/_authenticated/feedback/$id'
      path: '/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof AuthenticatedFeedbackIdRouteImport
      parentRoute: typeof AuthenticatedFeedbackRoute
    }
    '/_authenticated/coaching/new': {
      id: '/_authenticated/coaching/new'
      path: '/new'
      fullPath: '/coaching/new'
      preLoaderRoute: typeof AuthenticatedCoachingNewRouteImport
      parentRoute: typeof AuthenticatedCoachingRoute
    }
    '/_authenticated/coaching/$id': {
      id: '/_authenticated/coaching/$id'
      path: '/$id'
      fullPath: '/coaching/$id'
      preLoaderRoute: typeof AuthenticatedCoachingIdRouteImport
      parentRoute: typeof AuthenticatedCoachingRoute
    }
    '/api/public/hooks/feedback-escalations': {
      id: '/api/public/hooks/feedback-escalations'
      path: '/api/public/hooks/feedback-escalations'
      fullPath: '/api/public/hooks/feedback-escalations'
      preLoaderRoute: typeof ApiPublicHooksFeedbackEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-email-queue': {
      id: '/api/public/hooks/drain-email-queue'
      path: '/api/public/hooks/drain-email-queue'
      fullPath: '/api/public/hooks/drain-email-queue'
      preLoaderRoute: typeof ApiPublicHooksDrainEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-scheduled-reports': {
      id: '/api/public/hooks/dispatch-scheduled-reports'
      path: '/api/public/hooks/dispatch-scheduled-reports'
      fullPath: '/api/public/hooks/dispatch-scheduled-reports'
      preLoaderRoute: typeof ApiPublicHooksDispatchScheduledReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open/$id': {
      id: '/api/public/track/open/$id'
      path: '/api/public/track/open/$id'
      fullPath: '/api/public/track/open/$id'
      preLoaderRoute: typeof ApiPublicTrackOpenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click/$id': {
      id: '/api/public/track/click/$id'
      path: '/api/public/track/click/$id'
      fullPath: '/api/public/track/click/$id'
      preLoaderRoute: typeof ApiPublicTrackClickIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCoachingRouteChildren {
  AuthenticatedCoachingIdRoute: typeof AuthenticatedCoachingIdRoute
  AuthenticatedCoachingNewRoute: typeof AuthenticatedCoachingNewRoute
}

const AuthenticatedCoachingRouteChildren: AuthenticatedCoachingRouteChildren = {
  AuthenticatedCoachingIdRoute: AuthenticatedCoachingIdRoute,
  AuthenticatedCoachingNewRoute: AuthenticatedCoachingNewRoute,
}

const AuthenticatedCoachingRouteWithChildren =
  AuthenticatedCoachingRoute._addFileChildren(
    AuthenticatedCoachingRouteChildren,
  )

interface AuthenticatedFeedbackRouteChildren {
  AuthenticatedFeedbackIdRoute: typeof AuthenticatedFeedbackIdRoute
  AuthenticatedFeedbackNewRoute: typeof AuthenticatedFeedbackNewRoute
}

const AuthenticatedFeedbackRouteChildren: AuthenticatedFeedbackRouteChildren = {
  AuthenticatedFeedbackIdRoute: AuthenticatedFeedbackIdRoute,
  AuthenticatedFeedbackNewRoute: AuthenticatedFeedbackNewRoute,
}

const AuthenticatedFeedbackRouteWithChildren =
  AuthenticatedFeedbackRoute._addFileChildren(
    AuthenticatedFeedbackRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsSchedulesRoute: typeof AuthenticatedReportsSchedulesRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsSchedulesRoute: AuthenticatedReportsSchedulesRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCoachingRoute: typeof AuthenticatedCoachingRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCoachingRoute: AuthenticatedCoachingRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksDispatchScheduledReportsRoute:
    ApiPublicHooksDispatchScheduledReportsRoute,
  ApiPublicHooksDrainEmailQueueRoute: ApiPublicHooksDrainEmailQueueRoute,
  ApiPublicHooksFeedbackEscalationsRoute:
    ApiPublicHooksFeedbackEscalationsRoute,
  ApiPublicTrackClickIdRoute: ApiPublicTrackClickIdRoute,
  ApiPublicTrackOpenIdRoute: ApiPublicTrackOpenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
